package golden

import (
	"context"
	"encoding/base64"
	"io/fs"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/npmulder/ledgerly/internal/invoicing"
	"github.com/npmulder/ledgerly/internal/jurisdiction"
	"github.com/npmulder/ledgerly/web"
)

func TestInvoicePDFGoldens(t *testing.T) {
	requireChrome(t)
	if err := jurisdiction.LoadActive(jurisdiction.DefaultSelector); err != nil {
		t.Fatalf("LoadActive(%q) error = %v", jurisdiction.DefaultSelector, err)
	}

	server := startInvoicePrintServer(t)
	engine := invoicing.NewChromePDFEngine(server.URL)

	for _, tc := range []struct {
		name     string
		payload  invoicing.InvoicePrintPayload
		contains []string
	}{
		{
			name:    "invoice-reverse-charge-contoso",
			payload: reverseChargeContosoPayload(t),
			contains: []string{
				"Article 196",
				"\u20ac0.00",
				"0.8562",
				"SEPA BANK DETAILS",
				"Generated by Ledgerly",
			},
		},
		{
			name:    "invoice-domestic-fabrikam",
			payload: domesticFabrikamPayload(t),
			contains: []string{
				"Fabrikam Limited",
				"20% VAT",
				"\u20ac200.00",
				"SEPA BANK DETAILS",
				"Generated by Ledgerly",
			},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			pdfBytes, err := engine.RenderInvoicePDF(context.Background(), tc.payload)
			if err != nil {
				t.Fatalf("RenderInvoicePDF() error = %v", err)
			}
			text, err := extractPDFText(pdfBytes)
			if err != nil {
				t.Fatalf("extract invoice PDF text: %v", err)
			}
			for _, want := range tc.contains {
				if !strings.Contains(text, want) {
					t.Fatalf("PDF text missing %q:\n%s", want, text)
				}
			}
			PDF(t, tc.name, pdfBytes)
		})
	}
}

func startInvoicePrintServer(t testing.TB) *httptest.Server {
	t.Helper()

	assets, err := web.Dist()
	if err != nil {
		t.Fatalf("load embedded web assets: %v", err)
	}
	index, err := fs.ReadFile(assets, "index.html")
	if err != nil {
		t.Fatalf("invoice PDF golden requires built SPA assets: %v; run task web:build", err)
	}
	fileServer := http.FileServer(http.FS(assets))

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		cleanPath := strings.TrimPrefix(r.URL.Path, "/")
		if cleanPath != "" && !strings.HasPrefix(r.URL.Path, "/print/") {
			if _, err := fs.Stat(assets, cleanPath); err == nil {
				fileServer.ServeHTTP(w, r)
				return
			}
		}
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = w.Write(index)
	}))
	t.Cleanup(server.Close)
	return server
}

func reverseChargeContosoPayload(t testing.TB) invoicing.InvoicePrintPayload {
	t.Helper()

	issueDate := mustDate(t, "2026-03-01")
	vatRate, vatTaxYear := mustVATRate(t, issueDate)
	wording, err := jurisdiction.ReverseChargeWording("b2b_services_eu")
	if err != nil {
		t.Fatalf("ReverseChargeWording() error = %v", err)
	}
	note := wording.InvoiceWording
	number := "INV-2026-0008"
	lockID := "42"
	sentAt := time.Date(2026, 3, 1, 12, 0, 0, 0, time.UTC)

	payload := invoicePayloadBase(issueDate, "client-contoso", "Contoso BV")
	payload.Client.Address = invoicing.Address{
		Line1:      "Prins Hendrikkade 21",
		Locality:   "Amsterdam",
		PostalCode: "1012 TL",
		Country:    "Netherlands",
	}
	payload.Client.VATNumber = stringPtr("NL123456789B01")
	payload.Client.VATTreatment = invoicing.VATTreatmentReverseChargeEUB2B
	payload.Invoice.ID = "inv-rc-contoso"
	payload.Invoice.Number = &number
	payload.Invoice.ClientID = payload.Client.ID
	payload.Invoice.Status = invoicing.InvoiceStatusSent
	payload.Invoice.Currency = invoicing.CurrencyEUR
	payload.Invoice.LockID = &lockID
	payload.Invoice.SentAt = &sentAt
	payload.Invoice.VATTreatment = invoicing.VATTreatmentReverseChargeEUB2B
	payload.Invoice.Lines = []invoicing.InvoiceLine{{
		ID:          "line-rc-1",
		InvoiceID:   payload.Invoice.ID,
		Position:    1,
		Description: "EU B2B advisory services",
		Qty:         "1",
		UnitPrice:   money(420_000, invoicing.CurrencyEUR),
		LineTotal:   money(420_000, invoicing.CurrencyEUR),
	}}
	payload.Invoice.Totals = invoicing.InvoiceTotals{
		Subtotal: money(420_000, invoicing.CurrencyEUR),
		VAT:      money(0, invoicing.CurrencyEUR),
		Total:    money(420_000, invoicing.CurrencyEUR),
	}
	payload.VATRate = vatRate
	payload.VATTaxYear = vatTaxYear
	payload.ReverseChargeNote = &note
	payload.LockedRate = &invoicing.InvoicePrintLockedRate{ID: 42, Rate: "0.8562"}
	return payload
}

func domesticFabrikamPayload(t testing.TB) invoicing.InvoicePrintPayload {
	t.Helper()

	issueDate := mustDate(t, "2026-03-01")
	vatRate, vatTaxYear := mustVATRate(t, issueDate)
	number := "INV-2026-0009"
	lockID := "43"
	sentAt := time.Date(2026, 3, 1, 12, 0, 0, 0, time.UTC)

	payload := invoicePayloadBase(issueDate, "client-fabrikam", "Fabrikam Limited")
	payload.Client.Address = invoicing.Address{
		Line1:      "40 Circular Road",
		Locality:   "Douglas",
		PostalCode: "IM1 1AE",
		Country:    "Isle of Man",
	}
	payload.Client.VATNumber = stringPtr("GB987654321")
	payload.Client.VATTreatment = invoicing.VATTreatmentDomestic
	payload.Invoice.ID = "inv-domestic-fabrikam"
	payload.Invoice.Number = &number
	payload.Invoice.ClientID = payload.Client.ID
	payload.Invoice.Status = invoicing.InvoiceStatusSent
	payload.Invoice.Currency = invoicing.CurrencyEUR
	payload.Invoice.LockID = &lockID
	payload.Invoice.SentAt = &sentAt
	payload.Invoice.VATTreatment = invoicing.VATTreatmentDomestic
	payload.Invoice.Lines = []invoicing.InvoiceLine{{
		ID:          "line-domestic-1",
		InvoiceID:   payload.Invoice.ID,
		Position:    1,
		Description: "Domestic consultancy sprint",
		Qty:         "1",
		UnitPrice:   money(100_000, invoicing.CurrencyEUR),
		LineTotal:   money(100_000, invoicing.CurrencyEUR),
	}}
	payload.Invoice.Totals = invoicing.InvoiceTotals{
		Subtotal: money(100_000, invoicing.CurrencyEUR),
		VAT:      money(20_000, invoicing.CurrencyEUR),
		Total:    money(120_000, invoicing.CurrencyEUR),
	}
	payload.VATRate = vatRate
	payload.VATTaxYear = vatTaxYear
	payload.LockedRate = &invoicing.InvoicePrintLockedRate{ID: 43, Rate: "0.8562"}
	return payload
}

func invoicePayloadBase(issueDate time.Time, clientID string, clientName string) invoicing.InvoicePrintPayload {
	dueDate := issueDate.AddDate(0, 0, 30)
	return invoicing.InvoicePrintPayload{
		Client: invoicing.Client{
			ID:              clientID,
			Name:            clientName,
			DefaultCurrency: invoicing.CurrencyEUR,
			TermsDays:       30,
			CreatedAt:       issueDate,
		},
		Identity: invoicing.InvoicePrintIdentity{
			TradingName:   "Ledgerly Consulting",
			LegalName:     "Ledgerly Consulting Limited",
			CompanyNumber: "012345V",
			Address: invoicing.Address{
				Line1:      "Exchange House",
				Line2:      "54 Athol Street",
				Locality:   "Douglas",
				PostalCode: "IM1 1JD",
				Country:    "Isle of Man",
			},
			VATNumber:   stringPtr("GB123456789"),
			IBAN:        "GB29NWBK60161331926819",
			BIC:         "RBOSIMD2",
			BankName:    "Isle of Man Bank",
			LogoDataURI: stringPtr(invoiceGoldenLogoDataURI()),
		},
		Invoice: invoicing.Invoice{
			IssueDate: issueDate,
			DueDate:   dueDate,
			CreatedAt: issueDate,
			UpdatedAt: issueDate,
		},
	}
}

func invoiceGoldenLogoDataURI() string {
	const logo = `<svg xmlns="http://www.w3.org/2000/svg" width="308" height="116" viewBox="0 0 308 116"><rect width="308" height="116" rx="0" fill="#14213d"/><text x="32" y="72" fill="#ffffff" font-family="Arial, sans-serif" font-size="36" font-weight="700">Ledgerly</text><circle cx="260" cy="58" r="26" fill="#37b4a7"/></svg>`
	return "data:image/svg+xml;base64," + base64.StdEncoding.EncodeToString([]byte(logo))
}

func mustVATRate(t testing.TB, issueDate time.Time) (string, string) {
	t.Helper()

	rate, taxYear, err := jurisdiction.VATStandardRateForDate(issueDate)
	if err != nil {
		t.Fatalf("VATStandardRateForDate() error = %v", err)
	}
	return rate.String(), taxYear
}

func mustDate(t testing.TB, value string) time.Time {
	t.Helper()

	parsed, err := time.Parse(time.DateOnly, value)
	if err != nil {
		t.Fatalf("parse date %q: %v", value, err)
	}
	return parsed
}

func money(amount int64, currency invoicing.Currency) invoicing.Money {
	return invoicing.Money{Amount: amount, Currency: string(currency)}
}

func stringPtr(value string) *string {
	return &value
}
