DO $ledgerly$
BEGIN
	EXECUTE 'CREATE SCHEMA IF NOT EXISTS advisor';
	EXECUTE 'REVOKE ALL ON SCHEMA advisor FROM PUBLIC';

	IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ledgerly_advisor') THEN
		EXECUTE 'CREATE ROLE ledgerly_advisor LOGIN PASSWORD ''ledgerly_advisor''';
	END IF;

	EXECUTE 'ALTER ROLE ledgerly_advisor WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION';
	EXECUTE 'GRANT USAGE, CREATE ON SCHEMA advisor TO ledgerly_advisor';
	EXECUTE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA advisor TO ledgerly_advisor';
	EXECUTE 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA advisor TO ledgerly_advisor';
	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA advisor GRANT ALL PRIVILEGES ON TABLES TO ledgerly_advisor';
	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA advisor GRANT ALL PRIVILEGES ON SEQUENCES TO ledgerly_advisor';
	EXECUTE 'ALTER ROLE ledgerly_advisor SET search_path = advisor';
END
$ledgerly$;
