DO $ledgerly$
BEGIN
	EXECUTE 'CREATE SCHEMA IF NOT EXISTS moneyfx';
	EXECUTE 'REVOKE ALL ON SCHEMA moneyfx FROM PUBLIC';

	IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ledgerly_moneyfx') THEN
		EXECUTE 'CREATE ROLE ledgerly_moneyfx LOGIN PASSWORD ''ledgerly_moneyfx''';
	END IF;

	EXECUTE 'ALTER ROLE ledgerly_moneyfx WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION';
	EXECUTE 'GRANT USAGE, CREATE ON SCHEMA moneyfx TO ledgerly_moneyfx';
	EXECUTE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA moneyfx TO ledgerly_moneyfx';
	EXECUTE 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA moneyfx TO ledgerly_moneyfx';
	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA moneyfx GRANT ALL PRIVILEGES ON TABLES TO ledgerly_moneyfx';
	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA moneyfx GRANT ALL PRIVILEGES ON SEQUENCES TO ledgerly_moneyfx';
	EXECUTE 'ALTER ROLE ledgerly_moneyfx SET search_path = moneyfx';
END
$ledgerly$;
