CREATE TABLE IF NOT EXISTS moneyfx.rate_locks (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	ref text NOT NULL,
	from_currency text NOT NULL,
	to_currency text NOT NULL,
	rate numeric(38,18) NOT NULL,
	rate_date date NOT NULL,
	locked_at timestamptz NOT NULL DEFAULT now(),
	source text NOT NULL DEFAULT 'ECB',
	CONSTRAINT rate_locks_ref_not_blank CHECK (ref = btrim(ref) AND ref <> ''),
	CONSTRAINT rate_locks_ref_has_module CHECK (position(':' in ref) > 1 AND position(':' in ref) < length(ref)),
	CONSTRAINT rate_locks_from_currency_not_blank CHECK (from_currency = btrim(from_currency) AND from_currency <> ''),
	CONSTRAINT rate_locks_from_currency_upper CHECK (from_currency = upper(from_currency)),
	CONSTRAINT rate_locks_to_currency_not_blank CHECK (to_currency = btrim(to_currency) AND to_currency <> ''),
	CONSTRAINT rate_locks_to_currency_upper CHECK (to_currency = upper(to_currency)),
	CONSTRAINT rate_locks_rate_positive CHECK (rate > 0),
	CONSTRAINT rate_locks_source_ecb CHECK (source = 'ECB')
);

CREATE INDEX IF NOT EXISTS rate_locks_ref_id_idx
	ON moneyfx.rate_locks (ref, id DESC);

GRANT USAGE ON SCHEMA moneyfx TO PUBLIC;
GRANT SELECT ON moneyfx.ecb_rates TO PUBLIC;

REVOKE ALL PRIVILEGES ON moneyfx.rate_locks FROM PUBLIC;
REVOKE ALL PRIVILEGES ON moneyfx.rate_locks FROM ledgerly_moneyfx;
GRANT SELECT, INSERT ON moneyfx.rate_locks TO PUBLIC;
GRANT SELECT, INSERT ON moneyfx.rate_locks TO ledgerly_moneyfx;

REVOKE ALL PRIVILEGES ON SEQUENCE moneyfx.rate_locks_id_seq FROM PUBLIC;
REVOKE ALL PRIVILEGES ON SEQUENCE moneyfx.rate_locks_id_seq FROM ledgerly_moneyfx;
GRANT USAGE, SELECT ON SEQUENCE moneyfx.rate_locks_id_seq TO PUBLIC;
GRANT USAGE, SELECT ON SEQUENCE moneyfx.rate_locks_id_seq TO ledgerly_moneyfx;
