CREATE TABLE IF NOT EXISTS moneyfx.realised_fx (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	invoice_id text NOT NULL,
	lock_id bigint NOT NULL REFERENCES moneyfx.rate_locks(id) ON DELETE RESTRICT,
	settlement_date date NOT NULL,
	amount_gbp bigint NOT NULL,
	source_ref text NOT NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT realised_fx_invoice_id_not_blank CHECK (invoice_id = btrim(invoice_id) AND invoice_id <> ''),
	CONSTRAINT realised_fx_lock_id_positive CHECK (lock_id > 0),
	CONSTRAINT realised_fx_source_ref_not_blank CHECK (source_ref = btrim(source_ref) AND source_ref <> ''),
	CONSTRAINT realised_fx_invoice_lock_unique UNIQUE (invoice_id, lock_id)
);

COMMENT ON TABLE moneyfx.realised_fx IS
	'Deduplication ledger for realised FX settlement handling, keyed by invoice and immutable rate lock.';
COMMENT ON COLUMN moneyfx.realised_fx.amount_gbp IS
	'Realised FX amount in GBP pence; positive is a gain, negative is a loss, zero means no ledger entry/event was needed.';

CREATE INDEX IF NOT EXISTS realised_fx_invoice_id_idx
	ON moneyfx.realised_fx (invoice_id);

GRANT USAGE ON SCHEMA moneyfx TO PUBLIC;
REVOKE ALL PRIVILEGES ON moneyfx.realised_fx FROM PUBLIC;
REVOKE ALL PRIVILEGES ON moneyfx.realised_fx FROM ledgerly_moneyfx;
GRANT SELECT, INSERT ON moneyfx.realised_fx TO PUBLIC;
GRANT SELECT, INSERT ON moneyfx.realised_fx TO ledgerly_moneyfx;

REVOKE ALL PRIVILEGES ON SEQUENCE moneyfx.realised_fx_id_seq FROM PUBLIC;
REVOKE ALL PRIVILEGES ON SEQUENCE moneyfx.realised_fx_id_seq FROM ledgerly_moneyfx;
GRANT USAGE, SELECT ON SEQUENCE moneyfx.realised_fx_id_seq TO PUBLIC;
GRANT USAGE, SELECT ON SEQUENCE moneyfx.realised_fx_id_seq TO ledgerly_moneyfx;
