DO $ledgerly$
BEGIN
	EXECUTE 'CREATE SCHEMA IF NOT EXISTS ledger';
	EXECUTE 'REVOKE ALL ON SCHEMA ledger FROM PUBLIC';

	IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ledgerly_ledger') THEN
		EXECUTE 'CREATE ROLE ledgerly_ledger LOGIN PASSWORD ''ledgerly_ledger''';
	END IF;

	EXECUTE 'ALTER ROLE ledgerly_ledger WITH LOGIN PASSWORD ''ledgerly_ledger'' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION';
	EXECUTE 'GRANT USAGE, CREATE ON SCHEMA ledger TO ledgerly_ledger';
	EXECUTE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ledger TO ledgerly_ledger';
	EXECUTE 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ledger TO ledgerly_ledger';
	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA ledger GRANT ALL PRIVILEGES ON TABLES TO ledgerly_ledger';
	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA ledger GRANT ALL PRIVILEGES ON SEQUENCES TO ledgerly_ledger';
	EXECUTE 'ALTER ROLE ledgerly_ledger SET search_path = ledger';
END
$ledgerly$;
