DO $ledgerly$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_type t
		JOIN pg_namespace n ON n.oid = t.typnamespace
		WHERE n.nspname = 'ledger'
			AND t.typname = 'account_type'
	) THEN
		CREATE TYPE ledger.account_type AS ENUM (
			'asset',
			'liability',
			'equity',
			'income',
			'expense'
		);
	END IF;
END
$ledgerly$;

CREATE TABLE IF NOT EXISTS ledger.accounts (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	code text NOT NULL UNIQUE,
	name text NOT NULL,
	type ledger.account_type NOT NULL,
	currency text,
	created_at timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT accounts_code_not_blank CHECK (code = btrim(code) AND code <> ''),
	CONSTRAINT accounts_code_stable CHECK (code = lower(code)),
	CONSTRAINT accounts_name_not_blank CHECK (name = btrim(name) AND name <> ''),
	CONSTRAINT accounts_currency_iso CHECK (currency IS NULL OR currency ~ '^[A-Z]{3}$')
);

COMMENT ON TABLE ledger.accounts IS
	'Chart of accounts. Cash accounts are intentionally not seeded; banking creates real cash accounts through ledger.EnsureAccount.';

CREATE OR REPLACE FUNCTION ledger.ensure_account(
	p_code text,
	p_name text,
	p_type text,
	p_currency text
)
RETURNS TABLE (
	account_code text,
	account_name text,
	account_type text,
	account_currency text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ledger, pg_temp
AS $ledgerly$
BEGIN
	RETURN QUERY
	INSERT INTO ledger.accounts AS a (code, name, type, currency)
	VALUES (p_code, p_name, p_type::ledger.account_type, p_currency)
	ON CONFLICT (code) DO NOTHING
	RETURNING a.code, a.name, a.type::text, a.currency;

	IF FOUND THEN
		RETURN;
	END IF;

	RETURN QUERY
	SELECT a.code, a.name, a.type::text, a.currency
	FROM ledger.accounts AS a
	WHERE a.code = p_code;
END;
$ledgerly$;

COMMENT ON FUNCTION ledger.ensure_account(text, text, text, text) IS
	'Controlled cross-module entrypoint for idempotent ledger account creation.';

CREATE TABLE IF NOT EXISTS ledger.journal_entries (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	date date NOT NULL,
	description text NOT NULL,
	source_module text NOT NULL,
	source_ref text NOT NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT journal_entries_description_not_blank CHECK (description = btrim(description) AND description <> ''),
	CONSTRAINT journal_entries_source_module_not_blank CHECK (source_module = btrim(source_module) AND source_module <> ''),
	CONSTRAINT journal_entries_source_ref_not_blank CHECK (source_ref = btrim(source_ref) AND source_ref <> '')
);

CREATE INDEX IF NOT EXISTS journal_entries_date_id_idx
	ON ledger.journal_entries (date, id);
CREATE INDEX IF NOT EXISTS journal_entries_source_idx
	ON ledger.journal_entries (source_module, source_ref);

CREATE TABLE IF NOT EXISTS ledger.postings (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	entry_id bigint NOT NULL REFERENCES ledger.journal_entries(id) ON DELETE RESTRICT,
	account_code text NOT NULL REFERENCES ledger.accounts(code) ON DELETE RESTRICT,
	amount bigint NOT NULL,
	currency text NOT NULL,
	amount_gbp bigint NOT NULL,
	CONSTRAINT postings_currency_iso CHECK (currency ~ '^[A-Z]{3}$')
);

CREATE INDEX IF NOT EXISTS postings_entry_id_idx
	ON ledger.postings (entry_id, id);
CREATE INDEX IF NOT EXISTS postings_account_code_idx
	ON ledger.postings (account_code, entry_id, id);

INSERT INTO ledger.accounts (code, name, type, currency)
VALUES
	('1100-debtors-eur', 'Trade debtors EUR', 'asset', 'EUR'),
	('1101-debtors-gbp', 'Trade debtors GBP', 'asset', 'GBP'),
	('2200-vat-control', 'VAT control', 'liability', NULL),
	('2300-directors-loan', 'Director''s loan account', 'liability', 'GBP'),
	('3000-retained-earnings', 'Retained earnings', 'equity', 'GBP'),
	('4000-sales', 'Sales', 'income', NULL),
	('4900-fx-gain-loss', 'Realised FX gain/loss', 'income', 'GBP'),
	('5000-fees', 'Fees', 'expense', NULL),
	('5010-software', 'Software', 'expense', NULL),
	('5020-travel', 'Travel', 'expense', NULL),
	('5030-office', 'Office', 'expense', NULL)
ON CONFLICT (code) DO NOTHING;

ALTER DEFAULT PRIVILEGES IN SCHEMA ledger
	REVOKE ALL PRIVILEGES ON TABLES FROM ledgerly_ledger;
ALTER DEFAULT PRIVILEGES IN SCHEMA ledger
	GRANT SELECT, INSERT ON TABLES TO ledgerly_ledger;
ALTER DEFAULT PRIVILEGES IN SCHEMA ledger
	REVOKE ALL PRIVILEGES ON SEQUENCES FROM ledgerly_ledger;
ALTER DEFAULT PRIVILEGES IN SCHEMA ledger
	GRANT USAGE, SELECT ON SEQUENCES TO ledgerly_ledger;

GRANT USAGE ON SCHEMA ledger TO PUBLIC;
REVOKE ALL ON FUNCTION ledger.ensure_account(text, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION ledger.ensure_account(text, text, text, text) TO PUBLIC;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA ledger FROM ledgerly_ledger;
GRANT SELECT, INSERT ON ledger.accounts TO ledgerly_ledger;
GRANT SELECT, INSERT ON ledger.journal_entries TO ledgerly_ledger;
GRANT SELECT, INSERT ON ledger.postings TO ledgerly_ledger;

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ledger FROM ledgerly_ledger;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ledger TO ledgerly_ledger;
