DO $ledgerly$
BEGIN
	EXECUTE 'CREATE SCHEMA IF NOT EXISTS reports';
	EXECUTE 'REVOKE ALL ON SCHEMA reports FROM PUBLIC';

	IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ledgerly_reports') THEN
		EXECUTE 'CREATE ROLE ledgerly_reports LOGIN PASSWORD ''ledgerly_reports''';
	END IF;

	EXECUTE 'ALTER ROLE ledgerly_reports WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION';
	EXECUTE 'GRANT USAGE, CREATE ON SCHEMA reports TO ledgerly_reports';
	EXECUTE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA reports TO ledgerly_reports';
	EXECUTE 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA reports TO ledgerly_reports';
	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA reports GRANT ALL PRIVILEGES ON TABLES TO ledgerly_reports';
	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA reports GRANT ALL PRIVILEGES ON SEQUENCES TO ledgerly_reports';
	EXECUTE 'ALTER ROLE ledgerly_reports SET search_path = reports';
END
$ledgerly$;
