DO $ledgerly$
BEGIN
	EXECUTE 'CREATE SCHEMA IF NOT EXISTS audit';
	EXECUTE 'REVOKE ALL ON SCHEMA audit FROM PUBLIC';

	IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ledgerly_audit') THEN
		EXECUTE 'CREATE ROLE ledgerly_audit LOGIN PASSWORD ''ledgerly_audit''';
	END IF;

	EXECUTE 'ALTER ROLE ledgerly_audit WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION';
	EXECUTE 'GRANT USAGE, CREATE ON SCHEMA audit TO ledgerly_audit';
	EXECUTE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA audit TO ledgerly_audit';
	EXECUTE 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA audit TO ledgerly_audit';
	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT ALL PRIVILEGES ON TABLES TO ledgerly_audit';
	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT ALL PRIVILEGES ON SEQUENCES TO ledgerly_audit';
	EXECUTE 'ALTER ROLE ledgerly_audit SET search_path = audit';
END
$ledgerly$;

CREATE TABLE IF NOT EXISTS audit.entries (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	module text NOT NULL,
	entity text NOT NULL,
	entity_id text NOT NULL,
	actor text NOT NULL,
	occurred_at timestamptz NOT NULL DEFAULT now(),
	diff jsonb NOT NULL,
	CONSTRAINT entries_module_nonempty CHECK (module = btrim(module) AND module <> ''),
	CONSTRAINT entries_entity_nonempty CHECK (entity = btrim(entity) AND entity <> ''),
	CONSTRAINT entries_entity_id_nonempty CHECK (entity_id = btrim(entity_id) AND entity_id <> ''),
	CONSTRAINT entries_actor_nonempty CHECK (actor = btrim(actor) AND actor <> ''),
	CONSTRAINT entries_diff_object CHECK (jsonb_typeof(diff) = 'object')
);

CREATE INDEX IF NOT EXISTS entries_entity_occurred_idx
	ON audit.entries (module, entity, entity_id, occurred_at DESC, id DESC);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA audit TO ledgerly_audit;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA audit TO ledgerly_audit;
