DO $ledgerly$
BEGIN
	EXECUTE 'CREATE SCHEMA IF NOT EXISTS dla';
	EXECUTE 'REVOKE ALL ON SCHEMA dla FROM PUBLIC';

	IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ledgerly_dla') THEN
		EXECUTE 'CREATE ROLE ledgerly_dla LOGIN PASSWORD ''ledgerly_dla''';
	END IF;

	EXECUTE 'ALTER ROLE ledgerly_dla WITH LOGIN PASSWORD ''ledgerly_dla'' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION';
	EXECUTE 'GRANT USAGE, CREATE ON SCHEMA dla TO ledgerly_dla';
	EXECUTE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA dla TO ledgerly_dla';
	EXECUTE 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA dla TO ledgerly_dla';
	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA dla GRANT ALL PRIVILEGES ON TABLES TO ledgerly_dla';
	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA dla GRANT ALL PRIVILEGES ON SEQUENCES TO ledgerly_dla';
	EXECUTE 'ALTER ROLE ledgerly_dla SET search_path = dla';
END
$ledgerly$;
