DO $ledgerly$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_type t
		JOIN pg_namespace n ON n.oid = t.typnamespace
		WHERE n.nspname = 'dla'
			AND t.typname = 'entry_kind'
	) THEN
		CREATE TYPE dla.entry_kind AS ENUM (
			'drawing',
			'repayment',
			'expense-owed'
		);
	END IF;
END
$ledgerly$;

CREATE TABLE IF NOT EXISTS dla.dla_entries (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	date date NOT NULL,
	kind dla.entry_kind NOT NULL,
	description text NOT NULL,
	amount bigint NOT NULL,
	currency text NOT NULL DEFAULT 'GBP',
	source text NOT NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT dla_entries_description_not_blank CHECK (description = btrim(description) AND description <> ''),
	CONSTRAINT dla_entries_amount_positive CHECK (amount > 0),
	CONSTRAINT dla_entries_currency_gbp CHECK (currency = 'GBP'),
	CONSTRAINT dla_entries_source_not_blank CHECK (source = btrim(source) AND source <> ''),
	CONSTRAINT dla_entries_source_key UNIQUE (source)
);

COMMENT ON TABLE dla.dla_entries IS
	'Append-only presentation ledger for director loan activity. Running balances are derived by query, never stored.';

CREATE INDEX IF NOT EXISTS dla_entries_date_id_idx
	ON dla.dla_entries (date, id);

GRANT USAGE ON SCHEMA dla TO PUBLIC;

REVOKE ALL PRIVILEGES ON dla.dla_entries FROM PUBLIC;
REVOKE ALL PRIVILEGES ON dla.dla_entries FROM ledgerly_dla;
GRANT SELECT, INSERT ON dla.dla_entries TO PUBLIC;
GRANT SELECT, INSERT ON dla.dla_entries TO ledgerly_dla;

REVOKE ALL PRIVILEGES ON SEQUENCE dla.dla_entries_id_seq FROM PUBLIC;
REVOKE ALL PRIVILEGES ON SEQUENCE dla.dla_entries_id_seq FROM ledgerly_dla;
GRANT USAGE, SELECT ON SEQUENCE dla.dla_entries_id_seq TO PUBLIC;
GRANT USAGE, SELECT ON SEQUENCE dla.dla_entries_id_seq TO ledgerly_dla;
