DO $ledgerly$
BEGIN
	EXECUTE 'CREATE SCHEMA IF NOT EXISTS banking';
	EXECUTE 'REVOKE ALL ON SCHEMA banking FROM PUBLIC';

	IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ledgerly_banking') THEN
		EXECUTE 'CREATE ROLE ledgerly_banking LOGIN PASSWORD ''ledgerly_banking''';
	END IF;

	EXECUTE 'ALTER ROLE ledgerly_banking WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION';
	EXECUTE 'GRANT USAGE, CREATE ON SCHEMA banking TO ledgerly_banking';
	EXECUTE 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA banking TO ledgerly_banking';
	EXECUTE 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA banking TO ledgerly_banking';
	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA banking GRANT ALL PRIVILEGES ON TABLES TO ledgerly_banking';
	EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA banking GRANT ALL PRIVILEGES ON SEQUENCES TO ledgerly_banking';
	EXECUTE 'ALTER ROLE ledgerly_banking SET search_path = banking';
END
$ledgerly$;
