DO $ledgerly$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_type t
		JOIN pg_namespace n ON n.oid = t.typnamespace
		WHERE n.nspname = 'banking'
			AND t.typname = 'transaction_state'
	) THEN
		CREATE TYPE banking.transaction_state AS ENUM (
			'unreconciled',
			'suggested',
			'reconciled',
			'excluded'
		);
	END IF;
END
$ledgerly$;

CREATE TABLE IF NOT EXISTS banking.bank_accounts (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text NOT NULL,
	provider text NOT NULL,
	currency text NOT NULL,
	ledger_account_code text NOT NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT bank_accounts_name_not_blank CHECK (name = btrim(name) AND name <> ''),
	CONSTRAINT bank_accounts_provider_check CHECK (provider IN ('revolut')),
	CONSTRAINT bank_accounts_currency_check CHECK (currency IN ('GBP', 'EUR')),
	CONSTRAINT bank_accounts_ledger_account_code_not_blank CHECK (ledger_account_code = btrim(ledger_account_code) AND ledger_account_code <> ''),
	CONSTRAINT bank_accounts_ledger_account_code_stable CHECK (ledger_account_code = lower(ledger_account_code)),
	CONSTRAINT bank_accounts_provider_name_currency_unique UNIQUE (provider, name, currency),
	CONSTRAINT bank_accounts_ledger_account_code_unique UNIQUE (ledger_account_code)
);

CREATE TABLE IF NOT EXISTS banking.import_batches (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	account_id bigint NOT NULL REFERENCES banking.bank_accounts(id) ON DELETE RESTRICT,
	filename text NOT NULL,
	imported_at timestamptz NOT NULL DEFAULT now(),
	total_rows integer NOT NULL DEFAULT 0,
	new_rows integer NOT NULL DEFAULT 0,
	duplicate_rows integer NOT NULL DEFAULT 0,
	CONSTRAINT import_batches_filename_not_blank CHECK (filename = btrim(filename) AND filename <> ''),
	CONSTRAINT import_batches_row_counts_nonnegative CHECK (total_rows >= 0 AND new_rows >= 0 AND duplicate_rows >= 0),
	CONSTRAINT import_batches_row_counts_match CHECK (total_rows = new_rows + duplicate_rows)
);

CREATE INDEX IF NOT EXISTS import_batches_account_imported_idx
	ON banking.import_batches (account_id, imported_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS banking.transactions (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	account_id bigint NOT NULL REFERENCES banking.bank_accounts(id) ON DELETE RESTRICT,
	date date NOT NULL,
	amount bigint NOT NULL,
	currency text NOT NULL,
	payee text NOT NULL,
	reference text NOT NULL,
	provider_meta jsonb NOT NULL DEFAULT '{}'::jsonb,
	import_batch_id bigint NOT NULL REFERENCES banking.import_batches(id) ON DELETE RESTRICT,
	state banking.transaction_state NOT NULL DEFAULT 'unreconciled',
	dedupe_hash text NOT NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT transactions_currency_check CHECK (currency IN ('GBP', 'EUR')),
	CONSTRAINT transactions_payee_not_blank CHECK (payee = btrim(payee) AND payee <> ''),
	CONSTRAINT transactions_reference_trimmed CHECK (reference = btrim(reference)),
	CONSTRAINT transactions_provider_meta_object CHECK (jsonb_typeof(provider_meta) = 'object'),
	CONSTRAINT transactions_dedupe_hash_sha256 CHECK (dedupe_hash ~ '^[0-9a-f]{64}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS transactions_dedupe_hash_uidx
	ON banking.transactions (dedupe_hash);
CREATE INDEX IF NOT EXISTS transactions_account_date_idx
	ON banking.transactions (account_id, date DESC, id DESC);
CREATE INDEX IF NOT EXISTS transactions_import_batch_idx
	ON banking.transactions (import_batch_id, id);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA banking TO ledgerly_banking;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA banking TO ledgerly_banking;
