DO $ledgerly$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_type t
		JOIN pg_namespace n ON n.oid = t.typnamespace
		WHERE n.nspname = 'banking'
			AND t.typname = 'suggestion_kind'
	) THEN
		CREATE TYPE banking.suggestion_kind AS ENUM (
			'invoice-match',
			'dla',
			'payee-rule'
		);
	END IF;

	IF NOT EXISTS (
		SELECT 1
		FROM pg_type t
		JOIN pg_namespace n ON n.oid = t.typnamespace
		WHERE n.nspname = 'banking'
			AND t.typname = 'payee_rule_match_mode'
	) THEN
		CREATE TYPE banking.payee_rule_match_mode AS ENUM (
			'exact',
			'contains'
		);
	END IF;

	IF NOT EXISTS (
		SELECT 1
		FROM pg_type t
		JOIN pg_namespace n ON n.oid = t.typnamespace
		WHERE n.nspname = 'banking'
			AND t.typname = 'payee_rule_created_from'
	) THEN
		CREATE TYPE banking.payee_rule_created_from AS ENUM (
			'recode',
			'manual'
		);
	END IF;
END
$ledgerly$;

CREATE TABLE IF NOT EXISTS banking.transaction_state_changes (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	txn_id bigint NOT NULL REFERENCES banking.transactions(id) ON DELETE RESTRICT,
	from_state banking.transaction_state NOT NULL,
	to_state banking.transaction_state NOT NULL,
	changed_at timestamptz NOT NULL DEFAULT now(),
	actor text NOT NULL,
	CONSTRAINT transaction_state_changes_actor_not_blank CHECK (actor = btrim(actor) AND actor <> ''),
	CONSTRAINT transaction_state_changes_real_change CHECK (from_state <> to_state)
);

CREATE INDEX IF NOT EXISTS transaction_state_changes_txn_idx
	ON banking.transaction_state_changes (txn_id, changed_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS transaction_state_changes_to_state_idx
	ON banking.transaction_state_changes (to_state, changed_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS transactions_state_account_date_idx
	ON banking.transactions (state, account_id, date DESC, id DESC);

CREATE TABLE IF NOT EXISTS banking.suggestions (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	txn_id bigint NOT NULL REFERENCES banking.transactions(id) ON DELETE RESTRICT,
	kind banking.suggestion_kind NOT NULL,
	confidence numeric(4,3) NOT NULL,
	target text NOT NULL,
	explanation text NOT NULL,
	created_by text NOT NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	superseded_at timestamptz,
	CONSTRAINT suggestions_confidence_range CHECK (confidence >= 0 AND confidence <= 1),
	CONSTRAINT suggestions_target_not_blank CHECK (target = btrim(target) AND target <> ''),
	CONSTRAINT suggestions_explanation_not_blank CHECK (explanation = btrim(explanation) AND explanation <> ''),
	CONSTRAINT suggestions_created_by_not_blank CHECK (created_by = btrim(created_by) AND created_by <> ''),
	CONSTRAINT suggestions_superseded_after_created CHECK (superseded_at IS NULL OR superseded_at >= created_at)
);

CREATE UNIQUE INDEX IF NOT EXISTS suggestions_active_txn_uidx
	ON banking.suggestions (txn_id)
	WHERE superseded_at IS NULL;
CREATE INDEX IF NOT EXISTS suggestions_txn_history_idx
	ON banking.suggestions (txn_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS suggestions_active_kind_idx
	ON banking.suggestions (kind, confidence DESC, created_at DESC, id DESC)
	WHERE superseded_at IS NULL;

CREATE TABLE IF NOT EXISTS banking.payee_rules (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	matcher text NOT NULL,
	match_mode banking.payee_rule_match_mode NOT NULL,
	account_code text NOT NULL,
	times_applied integer NOT NULL DEFAULT 0,
	last_applied_at timestamptz,
	created_from banking.payee_rule_created_from NOT NULL,
	created_at timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT payee_rules_matcher_not_blank CHECK (matcher = btrim(matcher) AND matcher <> ''),
	CONSTRAINT payee_rules_matcher_normalized CHECK (matcher = lower(matcher)),
	CONSTRAINT payee_rules_account_code_not_blank CHECK (account_code = btrim(account_code) AND account_code <> ''),
	CONSTRAINT payee_rules_times_applied_nonnegative CHECK (times_applied >= 0),
	CONSTRAINT payee_rules_last_applied_requires_count CHECK (last_applied_at IS NULL OR times_applied > 0)
);

CREATE INDEX IF NOT EXISTS payee_rules_matcher_idx
	ON banking.payee_rules (match_mode, matcher);
CREATE INDEX IF NOT EXISTS payee_rules_applied_idx
	ON banking.payee_rules (times_applied DESC, last_applied_at DESC NULLS LAST, id);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA banking TO ledgerly_banking;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA banking TO ledgerly_banking;
