CREATE TABLE IF NOT EXISTS banking.match_engine_runs (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	trigger text NOT NULL,
	txns_evaluated bigint[] NOT NULL DEFAULT '{}'::bigint[],
	created_at timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT match_engine_runs_trigger_check CHECK (
		trigger IN ('import-completion', 'invoicing.InvoiceSent', 'manual-refresh')
	),
	CONSTRAINT match_engine_runs_txns_no_null CHECK (array_position(txns_evaluated, NULL) IS NULL)
);

CREATE INDEX IF NOT EXISTS match_engine_runs_trigger_created_idx
	ON banking.match_engine_runs (trigger, created_at DESC, id DESC);

ALTER TABLE banking.suggestions
	ADD COLUMN IF NOT EXISTS auto_postable boolean NOT NULL DEFAULT false;

CREATE UNIQUE INDEX IF NOT EXISTS payee_rules_matcher_mode_account_uidx
	ON banking.payee_rules (matcher, match_mode, account_code);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA banking TO ledgerly_banking;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA banking TO ledgerly_banking;
