CREATE TABLE IF NOT EXISTS banking.receipts (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	transaction_id bigint NOT NULL REFERENCES banking.transactions(id) ON DELETE CASCADE,
	asset_ref text NOT NULL,
	filename text NOT NULL,
	mime text NOT NULL,
	size bigint NOT NULL,
	uploaded_at timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT receipts_transaction_unique UNIQUE (transaction_id),
	CONSTRAINT receipts_asset_ref_not_blank CHECK (asset_ref = btrim(asset_ref) AND asset_ref <> ''),
	CONSTRAINT receipts_filename_not_blank CHECK (filename = btrim(filename) AND filename <> ''),
	CONSTRAINT receipts_mime_check CHECK (mime IN ('application/pdf', 'image/png', 'image/jpeg')),
	CONSTRAINT receipts_size_positive CHECK (size > 0)
);

CREATE INDEX IF NOT EXISTS receipts_uploaded_at_idx
	ON banking.receipts (uploaded_at DESC, id DESC);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA banking TO ledgerly_banking;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA banking TO ledgerly_banking;
